language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
branches:
  only:
  - master
install:
- npm ci
before_script:
- psql -c 'create database "fitbot-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: fitbot-cedrus
  api_key:
    secure: 5KHn58PUm5EwCrXkI38GaMAnCyCD/2lhPE+vKmKmKDMeLBmjxGpvh8dyhO3PLda/NtYteVJjLTA+TmnHg2+EaoTIQr9hd3xkU1zErB7rUyJFpVDTE8hHjedd/FbXclu265NRCcCooCW1avHhlCTbwZ9fEDnGmMY+TP7XavO4oMBuqgJ5rj9QHK6x9NvFylzfUZ8A/AFJHuz4MuwT3hi46XSem1BQr5Wnk0el/TNaD3MO5WAFlUJoJj9NrDVoqbpo+HA8Mn+Y/Sjk1kvlBjVYc0+y9x1htFKLvlfHlrK4slEL7zCGDDlPwjaU4VjVDmEBBXzhhG/rnjnppoUatLzbjZi9Lcx+HcQiFYBzS0rH6mmC4CzEZHs3uhmcKNT2j321B0vrTyzFjpw0O8rlssTwHEcbWfIQwEdLo4ytHQmP8dqKy/CS3WSBzTs8XeQO1Dwbl0+/rm6IYV1p8sf4qMX0NF844jWeUiRtZPVsvNorJvrVllHhDe07m/t1zI6RfdF78kKSXCtYpbH5vkGVSyb2R6Pa6t0CDZo/Y7AAs2BmxTXTNj7FC4V3VbayqKQJlFWdkoysc7Acum3iKrXe3bmbuBpVViKV5fQGtyILWiUKbqEYfBe9MptY8ujKzau7J4AOgxrIM06OCo6yq6NhLRTO4v+wblIDLyafRBqyhGIo5WQ=
before_install:
- openssl aes-256-cbc -K $encrypted_7baab9c8a267_key -iv $encrypted_7baab9c8a267_iv
  -in fitbot.json.enc -out fitbot.json -d
