language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "fitbot-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: fitbot-cedrus
  api_key:
    secure: p3rH5BBDieIe2b1klhHO/9H3uYucGXuv3DivA8d2hChZAMPfjhM1fxYF6bfFaLZoaMtu+bi8TRjJaCdDkqjZW7I9gKt8daSGLCIGqGnWt+hKUTZUZlEHbAuGQYGyxCl4voWdnatHt4ufAMvl9Mew+2lkcW28qn9uuKCwOXKIPk3UA8N0RE6N8uQWURw2bvFujqB63qiORIyMSsNSMRT/5IuZDRAvhiEZdWgdbgMxH7JJ8ZhOjA8x4KfMC8Dz+y8RjV3e06CrbPSYq7/eV02VmGK1bbk1h3GLZfYTY/bQXmJSsAck5Hz81eri4ebwHCRFWFLHC59adZ9aH0SD26Nlhp/aJ/E6UzFEd4W3mvDcJlIHY4M+5hbXUTVXZaWGu6x33Hks5idFvDOwB2Hmjf5IL7RJuxyR/JoWMpymgqQ5WF2dP+KhZUa2W94xDJewojzQDmWyQPWKKABLelNGK+D1QeM9qNUcH0YnN+WZdm0Yns0I88P78e0dgZ0hsjLlz6K4g1JDw5985YBUmi4JT7IHJS812jjbdBugt9is/NEaNYcGZ3PlLofTS72M77lKXBTjvMLg/uW8lqXujpJUlYWgKHKh0JbQm0dkMtuJM7K7bcIfEJUMlHnopu8MKTuFa85mHpOH8I7UeidFuVl2NlpihJog5EDlwY9+8gSlenTpydA=
before_install:
- openssl aes-256-cbc -K $encrypted_7baab9c8a267_key -iv $encrypted_7baab9c8a267_iv
  -in fitbot-27335-b5d2662a2d65.json.enc -out fitbot-27335-b5d2662a2d65.json -d
- openssl aes-256-cbc -K $encrypted_7baab9c8a267_key -iv $encrypted_7baab9c8a267_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
